apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: approval
    name: approval-api
  spec:
    ports:
    - name: approval-api
      port: 8080
      targetPort: 3000
    selector:
      name: approval-api
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: approval
    name: approval-api
  spec:
    replicas: 1
    selector:
      name: approval-api
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: '9394'
          prometheus.io/scrape: 'true'
        labels:
          app: approval
          name: approval-api
        name: approval-api
      spec:
        containers:
        - env:
          - name: APP_NAME
            value: approval
          - name: CLOUD_WATCH_LOG_GROUP
            value: platform
          - name: CW_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: CW_AWS_ACCESS_KEY_ID
                name: cloudwatch
          - name: CW_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: CW_AWS_SECRET_ACCESS_KEY
                name: cloudwatch
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                key: hostname
                name: approval-db
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: approval-db
          - name: DATABASE_PORT
            value: '5432'
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: approval-db
          - name: PATH_PREFIX
            value: api
          - name: PGSSLMODE
            value: verify-full
          - name: PGSSLROOTCERT
            value: /etc/rds-certs/rds-cacert
          - name: QUEUE_HOST
            value: platform-mq-prod-kafka-bootstrap.platform-mq-prod.svc
          - name: QUEUE_NAME
            value: platform.approval
          - name: QUEUE_PORT
            value: '9092'
          - name: RBAC_URL
            value: http://rbac.rbac-prod.svc:8080
          - name: KIE_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                key: kie-server-user
                name: approval-pam-secrets
          - name: KIE_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: kie-server-pwd
                name: approval-pam-secrets
          - name: APPROVAL_WEB_LOGO
            value: https://www.redhat.com/profiles/rh/themes/redhatdotcom/img/logo-reverse.svg
          - name: APPROVAL_WEB_PRODUCT
            value: Hybrid Cloud Manager
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                key: encryption-key
                name: approval-api-secrets
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                key: secret-key
                name: approval-api-secrets
          image: approval-prod/approval-api:stable
          name: approval-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
          - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
          volumeMounts:
          - mountPath: /etc/rds-certs
            name: rds-client-ca
            readOnly: true
        volumes:
        - name: rds-client-ca
          secret:
            secretName: rds-client-ca
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - approval-api
        from:
          kind: ImageStreamTag
          name: approval-api:stable
          namespace: approval-prod
      type: ImageChange

parameters:
- name: IMAGE
  value: quay.io/cloudservices/approval-api
- name: IMAGE_TAG
  value: 123abc
